### ISSUE TITLE
Blueprint no longer works 

### ISSUE THREAD

**Issue by ancjsd** [Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices#9]
The blueprint no longer works for me:  if I attempt to use it to create a script, I can't scroll beyond "Select one of the following actions on your phone."  The problem  occurs whether I'm working in the companion app or a browser.  I'm running core version 2023.11 3.  This t's a great blueprint, so I'd love to be able to use it again.  Thanks!

**Comment by Grumblezz** [comment]
Hi ancjsd,

I think your looking at the wrong location, by clicking on the script itself.  


As I have added a new input for all of the automations when using the new option: _"Android Only - Notify using TTS whilst using Andriod Auto? (Optional)"_ :
![image](https://github.com/Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices/assets/74052665/5bb08edc-9539-4264-98e9-6b7012f5e625)

This input _"Select one of the following actions on your phone."_ can be seen in the Scripts area:
![image](https://github.com/Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices/assets/74052665/2ab59b95-9e7d-49c8-9c03-a5203326f21c)

Scroll down until the end and then you'll see the latest addition: 
![image](https://github.com/Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices/assets/74052665/76000af2-ee0d-4c98-b9ba-0a75e633adaa)


And so instead of clicking on the script it self, you should use it in the Automations or other Scripts, for example:
![image](https://github.com/Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices/assets/74052665/e2b15069-45b6-43fc-902c-5b048f965e4a)
